# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e3695e65f68dfe818957744314b69ea0ee4e3cd942c9fa6db1c6504b9605d7ffa607617c6d28ea7fd36c6022acf36c413d6a41ec608ca76b7ba4e4fd675aee2

test:
  secret_key_base: 8bae90256d5c5ada41da571fdf29a7eb958126dd37c8d3c1791412f0d754efb0376a17392116f9852233840c97619e9df7d9d50cdca661a9860bb8b4756d0da5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
